.github/workflows/pull_request.yaml
This PR is adding a Github Actions workflow triggered by PullRequests.
The Action is executing the Maven "verify" goal and publishing the test results via the github check api to the pull requests preventing a merge if tests are failing
Used Github Action: https://github.com/ScaCap/action-surefire-report
Example Result: https://github.com/FTKeV/sapl-test/pull/1
=> Add workflow for pull requests

.github/workflows/pull_request.yaml
ci: fix pull_request workflow when PR is coming from Dependabot (#28)
=> update dependabot branch with updated pull_request workflow to fix issues with the pull_request workflow started by dependabot

sapl-pdp-embedded/src/main/java/io/sapl/pdp/interceptors/ReportBuilderUtil.java, sapl-pdp-embedded/src/main/java/io/sapl/pdp/interceptors/ReportTextRenderUtil.java, sapl-spring-pdp-embedded/src/main/java/io/sapl/spring/pdp/embedded/EmbeddedPDPProperties.java
=> Fixed typos

.github/workflows/build_branch.yml, .github/workflows/build_documentation.yml, .github/workflows/build_master.yml, .github/workflows/pull_request.yaml, sapl-server-lt/Dockerfile
Adding version pinning to be compliant with best practice of tooling.
View [here](https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies) for explanation about this topic.
Manually setting hash on docker file and using https://app.stepsecurity.io/secureworkflow for workflows.
**THIS PR NEEDS TO BE TESTED WITH REPOSITORY OWNED ACTION RUNS!**
* ~~[ ] I have added tests to cover my changes.~~
=> chore: Add version pinning for workflows and docker files

CONTRIBUTING.md, README.md
Minor documentation adjustments and adding reference to default SBOM generation of GitHub.
TODO: Replace logo.
* ~~[ ] I have added tests to cover my changes.~~
=> docs: Resolve minor issues and add SBOM

sapl-documentation/src/asciidoc/sapl-reference.adoc, sapl-maven-plugin/README.md
This PR proposes changes to the SAPL documentation and the SAPL Maven Plugin Readme. The changes need to be reviewed before being merged.
A new Readme for the sapl-maven-plugin module gives a short description of the plugin and a quick guide how to get it started. Detailed information on how to configure the plugin is included in the SAPL documentation. Changes have been made to the description of the parameter "enableSonarReport" and a description of the parameter "failOnDisabledTests" was added. 
We decided to include the detailed description in the docs and keep the Readme short, as seen with the [spotbugs plugin](https://github.com/spotbugs/spotbugs-maven-plugin) and the [sonar plugin](https://github.com/SonarSource/sonar-scanner-maven) .
* [x ] I have updated the documentation …
=> Update SAPL Maven Plugin Documentation and Readme

README.md
Fixing minor mistake in #58.
-
=> docs: Resolve some failed styling in markdown

.github/workflows/scorecard.yml, README.md
=> Add openssf scorecards GitHub Action and add the badge in the README

README.md
The current logo used in README.md is not compliant with light themes, as the name is not properly contrasted with borders or other methods.
To resolve this issue, I would like to suggest with this PR the use of the simple logo without the name included. This is very independent of themes and reduces redundancy between the logo and the text.
I am setting the width of the logo to 100em (https://fonts.google.com/knowledge/glossary/em), as this a reasonable and scales with the configured font size.
Are you fine with this change or would you still prefer the name on the logo?
=> docs: replace logo to be compliant with other common theming

sapl-server-lt/Dockerfile
When creating a container image, there is no option to include your own configuration. This makes settings relating to TLS or authorization more difficult.
An additional CONFIG_FOLDER argument has been added to the Dockerfile. This means that "docker build --build-arg JAR_FILE=target/sapl-server-lt-3.0.0-SNAPSHOT.jar --build-arg CONFIG_FOLDER=config ." can be called as an optional parameter when creating an image.
This facilitates settings such as a separate keystore for the certificates or other user-specific settings.
=> Dockerfile with new parameter

sapl-lang/src/main/java/io/sapl/grammar/sapl/impl/RegexImplCustom.java
The *ImplCustom classes in io.sapl.grammar.sapl.impl are adding tracing to the created Val objects. The tracing normaly refers to the classes representing the corresponding parts of the sapl grammar. But RegexImplCustom uses the Regex class from the checkerframework instead of the Regex class from the sapl grammar, which is probably unintended.
Therefore sapl-lang directly depends on the checkerframework.
This PR changes the import in RegexImplCustom so that the tracing refers to the Regex class from sapl and sapl-lang does not directly depend on the checkerframework anymore.
=> Use the Regex class from sapl for the tracing in RegexImplCustom

.github/workflows/pull_request.yaml, .github/workflows/pull_request_fork.yaml, .github/workflows/sonar_analysis_fork.yaml, pom.xml, spotbugsExcludeFilter.xml
- Modifies pull_request workflow to include spotbugs and sonarcloud analysis and to be limited to pull requests from the own repository.
- Adds two new workflows for testing and analysing pull requests from forks. The SonarCloud analysis is triggered after the tests in the pull requests were successfull.
- Hardens the action for pull requests from forks against script injections by checking the branch name of the fork for suspicious characters.
- Adds a new profile "spotbugs" in the pom.xml for spotbugs analysis.
- Excludes the sapl-bom module from testing and analysis since it should not contain Java code.
=> SonarCloud analysis for Pull Requests

.github/workflows/sonar_analysis_fork.yaml, pom.xml
Moves sonar.organization from pom to sonar fork action
=> move sonar.organization from pom to action

sapl-server-lt/Dockerfile
Undo the Dockerfile changes with obsolete parameter CONFIG_FOLDER
Reverted changes to the Dockerfile so that the original configuration was restored. The CONFIG_FOLDER parameter has been removed from the Dockerfile. This parameter was obsolete and posed a risk to container security.
=> Undoing the Dockerfile changes

sapl-lang/src/test/java/io/sapl/grammar/tests/SaplParsingTests.java, sapl-lang/src/test/java/io/sapl/interpreter/DefaultSAPLInterpreterTransformationTests.java, sapl-maven-plugin/src/main/java/io/sapl/mavenplugin/test/coverage/report/html/HtmlLineCoverageReportGenerator.java
=> fix sonar issues

.github/workflows/pull_request_fork.yaml, .github/workflows/sonar_analysis_fork.yaml
- Removes the branch name of the fork from the fork workflows since it is not needed for the correct display of the SonarCloud analysis.
- Adds the compiled test classes to the SonarCloud analysis for forks. Without them, test classes are not included in the analysis.
=> Update workflow for Pull Requests from Forks

.github/workflows/scorecard.yml
Currently, the OSSF Scorecard cannot scan the branch protection rules.
To resolve this we require the usage of a dedicated token for this scan. 
https://github.com/ossf/scorecard-action#authentication-with-fine-grained-pat-optional
Creation of the token can be done following the description:
https://github.com/ossf/scorecard-action/blob/main/docs/authentication/fine-grained-auth-token.md
And expose this as a secret to the action named as `SCORECARD_TOKEN`.
View my result in my fork for an indication that it works:
https://securityscorecards.dev/viewer/?uri=github.com/flodet-me/sapl-policy-engine
**BEFORE MERGING THE TOKEN HAS TO BE AVAILABLE**
Be aware that we need to create a token with administrative read permission, which we might not want to.
=> enable OSSF scorecard evaluation with PAT

.github/workflows/pull_request.yaml
Fixes the broken workflow pull_request.yaml by adding the correct Sonar token and organization.
=> fix SonarCloud parameters in pull_request.yaml

sapl-lang/src/main/java/io/sapl/grammar/sapl/impl/ObjectImplCustom.java, sapl-lang/src/test/java/io/sapl/grammar/sapl/impl/ObjectImplCustomTests.java
Fields with values that are expressions with errors in object creation were simply dropped instead of propagating the error.
=> fix object error propagation

.github/workflows/pull_request.yaml, .github/workflows/pull_request_fork.yaml
This PR adds os windows and macos to the unit tests in the pr workflows. The SonarCloud analysis still only runs on ubuntu.
It also adds Java Version 21 to the test job.
=> Run unit tests additionally on windows and macos for pull requests

sapl-lang/src/main/java/io/sapl/grammar/GenerateSAPL.mwe2, sapl-vaadin-editor/src/main/java/io/sapl/vaadin/JsonEditor.java, sapl-vaadin-editor/src/main/java/io/sapl/vaadin/SaplEditor.java
update jquery to currently latest version 3.7.1 and codemirror5 to currently latest version 5.65.16
following functionality was tested with sapl-demo-playground and sapl-demo-web-editor
- code completion (ctrl+space)
- error messages for sapl and json editor
- code highlighting
=> update jquery and codemirror5 to currently latest version

sapl-test-lang/pom.xml, sapl-test-lang/src/main/java/io/sapl/test/grammar/GenerateSAPLTest.mwe2, sapl-test-lang/src/main/java/io/sapl/test/grammar/validation/SAPLTestValidator.java, sapl-test-lang/src/test/java/io/sapl/test/grammar/validation/SAPLTestValidatorTest.java
adjust xText setup, add additional validation for TestCase, add tests for all grammar validations
=> extend grammar validation and add tests for sapl-test-lang

.github/workflows/build_branch.yml
Modifies build_branch.yml to include all branches of the repo.
=> trigger build_branch.yml for all branches except master

sapl-vaadin-editor/src/main/java/io/sapl/vaadin/SaplTestEditor.java
like #100 update jquery and codemirror5 to currently latest versions in SaplTestEditor (#103)
=> update jquery and codemirror5 to currently latest versions in SaplTestEditor

.github/workflows/build_branch.yml
Adds the modified version of build_branch.yml to the enforce-schema branch. GitHuB uses the workflow files defined within the branches. Code analysis should now start automatically after new pushes to this branch.
=> enable automatic code analysis after pushes to this branch

sapl-lang/src/main/java/io/sapl/grammar/GenerateSAPL.mwe2, sapl-test-lang/src/main/java/io/sapl/test/grammar/GenerateSAPLTest.mwe2, sapl-vaadin-editor/src/main/java/io/sapl/vaadin/JsonEditor.java, sapl-vaadin-editor/src/main/java/io/sapl/vaadin/SaplEditor.java, sapl-vaadin-editor/src/main/java/io/sapl/vaadin/SaplTestEditor.java
=> jquery is no longer needed with current codemirror5 version but for xtext

.github/workflows/scorecard.yml
Current version does not detect fuzzing correctly. Bumping version to fix this.
For verification:
=> Update scorecard-action version to v2.3.1

sapl-ide/src/main/java/io/sapl/grammar/ide/contentassist/ExpressionSchemaResolver.java, sapl-ide/src/main/java/io/sapl/grammar/ide/contentassist/SchemaProposalGenerator.java, sapl-lang/pom.xml, sapl-lang/src/main/java/io/sapl/grammar/validation/SAPLValidator.java, sapl-lang/src/test/java/io/sapl/grammar/validation/SAPLValidatorTests.java, sapl-test/src/test/java/io/sapl/test/lang/PolicySetImplCustomCoverageTests.java
=> minor spelling and formatting

sapl-pdp-remote/src/main/java/io/sapl/pdp/remote/RemoteHttpPolicyDecisionPoint.java, sapl-pdp-remote/src/main/java/io/sapl/pdp/remote/RemoteRsocketPolicyDecisionPoint.java, sapl-pdp-remote/src/test/java/io/sapl/pdp/remote/RemoteHttpPolicyDecisionPointTests.java, sapl-pdp-remote/src/test/java/io/sapl/pdp/remote/RemoteRsocketDecisionPointServerIT.java, sapl-pdp-remote/src/test/java/io/sapl/pdp/remote/RemoteRsocketPolicyDecisionPointTests.java, sapl-server-lt/config/application.yml, sapl-webflux-endpoint/src/main/java/io/sapl/server/pdpcontroller/PDPController.java, sapl-webflux-endpoint/src/test/java/io/sapl/server/pdpcontroller/PDPControllerWithKeepaliveTests.java
This PR adds keepAlive support for http and rsocket.
=> Keep alive

sapl-pdp-remote/src/test/java/io/sapl/pdp/remote/RemoteHttpPolicyDecisionPointTests.java, sapl-pdp-remote/src/test/java/io/sapl/pdp/remote/RemoteRsocketPolicyDecisionPointTests.java, sapl-webflux-endpoint/src/main/java/io/sapl/server/pdpcontroller/PDPController.java
=> formatting

pom.xml, sapl-pdp-embedded/pom.xml
=> bump dependencies

pom.xml, sapl-test/src/main/java/io/sapl/test/dsl/interfaces/IntegrationTestConfiguration.java, sapl-test/src/main/java/io/sapl/test/dsl/interfaces/IntegrationTestPolicyResolver.java, sapl-test/src/main/java/io/sapl/test/dsl/interfaces/SaplTestInterpreter.java, sapl-test/src/main/java/io/sapl/test/dsl/interfaces/StepConstructor.java, sapl-test/src/main/java/io/sapl/test/dsl/interfaces/TestNode.java, sapl-test/src/main/java/io/sapl/test/dsl/interfaces/UnitTestPolicyResolver.java, sapl-test/src/main/java/io/sapl/test/dsl/setup/BaseTestAdapter.java
=> undo sonar source plugin version bump

.github/workflows/build_branch.yml, .github/workflows/build_master.yml
=> remove production profile from build

sapl-lang/src/main/java/io/sapl/grammar/sapl/impl/PolicySetImplCustom.java
=> fix ignored imports in policy set

.github/workflows/run_fuzz_tests.yml
Currently the score on the OSSF Scorecard is 0 due to the new workflow for fuzzing.
Introducing minimal fix to get the rating back to 10.
See the following result in my fork.
=> ci: Solve token permission issue with ossf scorecard

sapl-server-lt/README.md, sapl-server-lt/src/main/resources/application-docker.yml, sapl-server-lt/src/main/resources/application.yml
This PR updates the documentation for SAPL Server LT. Additionally, configurations for SAPL Server LT are transferred from the application.yml of the Docker profile to the standard profile, as they are also necessary in the standard profile. The loader.path configuration has been removed from both profiles.
=> Update documentation and customize configurations

sapl-lang/src/main/java/io/sapl/interpreter/DefaultSAPLInterpreter.java, sapl-lang/src/main/java/io/sapl/interpreter/InputStreamHelper.java, sapl-lang/src/test/java/io/sapl/interpreter/InputStreamHelperTests.java
I didn't change any logic in the code but refactored it a bit and tried to make it more utility class like.
=> trojan source: small refactoring

.github/workflows/build.yml, pom.xml
- fails maven build for tests at end
- set ups Node.js 20 for testing and deployment
- fails the build if there are javadoc warnings
=> Update build workflow

.github/workflows/build.yml
This PR replaces #152 due to changes introduced by #139 
Support nested maven project hierarchy in the sonarcloud analysis for PRs from forks.
The project has a flat hierarchy at the moment but this changes with https://github.com/heutelbeck/sapl-policy-engine/pull/132, where the projects for the eclipse plugin are nested into a subdirectory. This breaks the sonarcloud analysis at the moment, because the projects in the subdirectories are not included into the pr_build.zip which is generated by the pull_request_fork workflow.
With this PR all relevant directories are also included from subdirectories.
This should fix the sonarcloud analysis for https://github.com/heutelbeck/sapl-policy-engine/pull/132.
=> Support nested maven project hierarchy in the sonarcloud analysis for PRs from forks - No.2

.github/workflows/sonar_analysis_fork.yaml
SonarCloud checks of pull requests from forks are currently displayed on the master branch. This is because SonarCloud took the wrong commit sha when displaying its results. This should fix the issue.
=> fix: correctly assign SonarCloud checks of PRs from fork

pom.xml
This PR supplements #164 
The SonarQube URL is removed from pom.xml.
=> delete sonarqube property from pom.xml

.github/workflows/build.yml, .github/workflows/sonar_analysis_fork.yaml
The build workflow will now also run once a branch in the repository is created.
=> add trigger to build workflow

.github/workflows/build.yml, sapl-server-lt/README.md, sapl-server-lt/pom.xml
The SAPL Server LT documentation is updated. A Dockerfile is no longer required for the build of the Docker image, as this process is now realized via the Maven Spring Boot plugin and the builder.
* [] All new and existing tests passed.
=> Update documentation and change docker profile of SAPL Server LT

sapl-documentation/9_9_CodeCoverageReportsviatheSAPLMavenPlugin.md, sapl-maven-plugin/README.md, sapl-server-lt/README.md, sapl-webflux-endpoint/README.md
Updates SAPL documentation on SAPL Maven Plugin and links to the documentation.
=> update documentation and links

pom.xml, sapl-eclipse-plugin/sapl-eclipse-thirdparty/pom.xml, sapl-extensions-api/pom.xml, sapl-ide/pom.xml, sapl-lang/pom.xml, sapl-pdp-embedded/pom.xml
Add checksums during the package phase to the dependencies of sapl-eclipse-repository to satisfy the verification by tycho
=> Fix build warning "No digest algorithm is available to verify download of osgi.bundle"

.github/workflows/build.yml, sapl-eclipse-plugin/sapl-eclipse-feature/feature.xml, sapl-eclipse-plugin/sapl-eclipse-feature/pom.xml, sapl-eclipse-plugin/sapl-eclipse-repository/README.md, sapl-eclipse-plugin/sapl-eclipse-repository/category.xml, sapl-eclipse-plugin/sapl-eclipse-repository/pom.xml
Rename sapl-eclipse-feature to io.sapl.eclipse.feature so that the name is similar to other eclipse features and follows naming requirements.
=> Rename sapl-eclipse-feature to io.sapl.eclipse.feature

sapl-eclipse-plugin/sapl-eclipse-repository/pom.xml
Sign the sapl eclipse update site with gpg when the publish profile is active.
The signature is then visible during the installation of the plugin in eclipse:
=> Sign the sapl eclipse update site with gpg when the publish profile is active

.github/pull_request_template.md, CONTRIBUTING.md
- Adds information on SpotBugs as static code analysis tool.
- Adds information on signing commits and lets contributors know that it is mandatory.
=> add info on spotbugs and signing commits for contributors

sapl-server-lt/README.md, sapl-server-lt/pom.xml, sapl-server-lt/src/main/resources/application-docker.yml
Update the SAPL Server LT documentation. The focus is on adapting the section for Docker and Kubernetes. An additional variable for the config location is added for the creation of the Docker image. In the application-docker.yml, a property is removed that is not required.
=> Update documentation and change properties for docker of the SAPL Server LT

sapl-ide/pom.xml, sapl-lang/pom.xml, sapl-pdp-embedded/pom.xml
Relax versioned dependency on guava in the manifests to allow newer g…uava versions to avoid dependency issues at runtime-
=> Fix dependency issue for the eclipse plugin at runtime

sapl-server-lt/README.md, sapl-server-lt/kubernetes/sapl-server-lt-baremetal.yml, sapl-server-lt/kubernetes/sapl-server-lt.yml, sapl-server-lt/pom.xml
Update the SAPL Server LT documentation. Also adapt the current Kubernetes files to the 3.0.0-SNAPSHOT. Furthermore, the part of the creation of the Docker image of the SAPL Server LT is supplemented by two additional ENV.
=> Update documentation and Kubernetes files of the SAPL Server LT

pom.xml, sapl-eclipse-plugin/sapl-eclipse-thirdparty/pom.xml, sapl-eclipse-plugin/sapl-eclipse-ui/README.md
Fix the following eclipse warnings
- There is currently no execution that generates a manifest, consider adding an execution for one of the following goal: manifest.
- Plugin execution not covered by lifecycle configuration: org.eclipse.tycho:tycho-bnd-plugin:4.0.6:process
- Incremental updates are currently disabled, set supportIncrementalBuild=true to support automatic manifest updates for this project.
Add recommendations to the README of sapl-eclipse-ui for the development of the SAPL Eclipse plugin
=> Fix eclipse warnings

.github/workflows/ossf-scorecard.yml
My last PR #191 did contain old action references. This PR resolves this
=> Resolve version issue with scorecard

sapl-spring-security/README.md
=> Spring Security README

README.md, sapl-language-server/README.md
Extend documentation regarding IDE-Support for sapl files in the READMEs.
Add documentation on how to configure the SAPL language server in the Editor Kate.
=> Extend documentation regarding IDE-Support for sapl files in the READMEs

sapl-test/src/main/java/io/sapl/test/dsl/interpreter/DocumentInterpreter.java, sapl-test/src/main/java/io/sapl/test/integration/SaplIntegrationTestFixture.java, sapl-test/src/test/java/io/sapl/test/dsl/interpreter/DocumentInterpreterTests.java, sapl-test/src/test/java/io/sapl/test/integration/SaplIntegrationTestFixtureTests.java
Small fix for null PDP configuration handling
=> fix behaviour for null PDP configuration

sapl-lang/pom.xml, sapl-lang/src/main/java/io/sapl/functions/StandardFunctionLibrary.java, sapl-lang/src/test/java/io/sapl/functions/StandardFunctionLibraryTests.java
=> add set operations to standard library

sapl-test/README.md, sapl-test/src/main/java/io/sapl/test/dsl/setup/TestCase.java, sapl-test/src/test/java/io/sapl/test/dsl/setup/TestCaseTests.java
Adjust documentation and some error messages for changed structure.
=> Update Documentation and Error Messages for adjusted SAPLTest Structure

sapl-jwt/src/main/java/io/sapl/extension/jwt/JWTFunctionLibrary.java, sapl-lang/src/main/java/io/sapl/functions/FilterFunctionLibrary.java, sapl-lang/src/main/java/io/sapl/functions/LoggingFunctionLibrary.java, sapl-lang/src/main/java/io/sapl/functions/SchemaValidationLibrary.java, sapl-lang/src/main/java/io/sapl/functions/StandardFunctionLibrary.java, sapl-lang/src/main/java/io/sapl/functions/TemporalFunctionLibrary.java, sapl-mqtt-functions/src/main/java/io/sapl/extensions/mqtt/MqttFunctionLibrary.java
=> improve sapl online documentation
